import SeverityBadge from './SeverityBadge';
import RelativeTime from './RelativeTime';

const borderBySeverity = {
  critical: 'border-l-severity-critical',
  high: 'border-l-severity-high',
  moderate: 'border-l-severity-moderate',
  safe: 'border-l-severity-safe',
};

function normSeverity(s) {
  const v = (s || '').toLowerCase();
  if (['critical', 'high', 'moderate', 'safe'].includes(v)) return v;
  if (v === 'warning') return 'moderate';
  return 'safe';
}

// Map measurement type → category label and icon color token
const MEASUREMENT_CATEGORY = {
  // Air quality
  'pm2.5':        { label: 'Air Quality · PM2.5',    color: 'text-data-orange' },
  'pm10':         { label: 'Air Quality · PM10',     color: 'text-data-orange' },
  'aqi':          { label: 'Air Quality Index',      color: 'text-data-orange' },
  'no2':          { label: 'Air Quality · NO₂',      color: 'text-data-orange' },
  'so2':          { label: 'Air Quality · SO₂',      color: 'text-data-orange' },
  'co':           { label: 'Air Quality · CO',       color: 'text-data-orange' },
  'o3':           { label: 'Air Quality · Ozone',    color: 'text-data-orange' },
  // Temperature / heat
  'temperature':  { label: 'Temperature',            color: 'text-severity-high' },
  'heat index':   { label: 'Heat Index',             color: 'text-severity-critical' },
  'feels like':   { label: 'Feels Like Temp',        color: 'text-severity-high' },
  // Wind
  'wind speed':   { label: 'Wind Speed',             color: 'text-data-blue' },
  'wind gust':    { label: 'Wind Gust',              color: 'text-data-blue' },
  'wind':         { label: 'Wind',                   color: 'text-data-blue' },
  // Pressure
  'pressure':     { label: 'Barometric Pressure',    color: 'text-data-purple' },
  'atmosphericpressure': { label: 'Atmospheric Pressure', color: 'text-data-purple' },
  // Humidity
  'humidity':     { label: 'Humidity',               color: 'text-data-teal' },
  'relative humidity': { label: 'Relative Humidity', color: 'text-data-teal' },
  // Precipitation / water
  'precipitation':{ label: 'Precipitation',          color: 'text-data-blue' },
  'rainfall':     { label: 'Rainfall',               color: 'text-data-blue' },
  'water level':  { label: 'Water Level',            color: 'text-severity-critical' },
  // UV / radiation
  'uv index':     { label: 'UV Index',               color: 'text-severity-moderate' },
  'uvi':          { label: 'UV Index',               color: 'text-severity-moderate' },
  // Visibility / clouds
  'visibility':   { label: 'Visibility',             color: 'text-text-muted' },
  'cloud cover':  { label: 'Cloud Cover',            color: 'text-text-secondary' },
};

function getMeasurementCategory(measurement) {
  if (!measurement) return null;
  const key = measurement.toLowerCase().trim();
  // Try exact match first
  if (MEASUREMENT_CATEGORY[key]) return MEASUREMENT_CATEGORY[key];
  // Try partial match
  for (const [pattern, meta] of Object.entries(MEASUREMENT_CATEGORY)) {
    if (key.includes(pattern) || pattern.includes(key)) return meta;
  }
  return { label: measurement, color: 'text-text-secondary' };
}

function buildAlertMessage(alert) {
  // If the stored message is a real human message (not the auto-generated technical one), use it
  const raw = alert.message || '';
  const isAutoGenerated =
    raw.toLowerCase().startsWith('threshold breached:') ||
    raw.toLowerCase().startsWith('high sensor value') ||
    raw === '' ||
    raw.toLowerCase().startsWith('auto-generated');

  // Build a descriptive message following the user's template
  const parameter = alert.measurement || alert.alert_type || 'Reading';
  const location = alert.location_name || alert.region || 'System';
  const unit = alert.unit || '';
  const limitValue = alert.threshold_max ?? alert.trigger_value;

  let msg = `In ${location} this ${parameter} crossed the max limit ${
    limitValue != null ? Number(limitValue).toFixed(1) : 'threshold'
  } ${unit}`.trim();

  return msg;
}

export default function AlertCard({ alert, fullMessage = false, onClick, animationDelayMs = 0 }) {
  const sev = normSeverity(alert.severity || alert.alert_type);
  const borderClass = borderBySeverity[sev] || borderBySeverity.safe;
  const cat = getMeasurementCategory(alert.measurement || alert.alert_type || '');
  const displayMessage = buildAlertMessage(alert);

  return (
    <div
      role={onClick ? 'button' : undefined}
      onClick={onClick}
      className={`flex flex-col sm:flex-row sm:items-start gap-3 p-4 bg-surface-secondary border border-border-subtle border-l-4 ${borderClass} rounded-lg cursor-pointer hover:bg-surface-elevated transition-colors duration-200 animate-alert-card`}
      style={{ animationDelay: `${animationDelayMs}ms` }}
    >
      <div className="flex flex-col gap-1.5 shrink-0">
        <SeverityBadge severity={alert.severity || alert.alert_type} />
        {cat && (
          <span className={`text-[10px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded bg-surface-primary border border-border-subtle ${cat.color}`}>
            {cat.label}
          </span>
        )}
      </div>

      <div className="flex-1 min-w-0">
        <p className={`text-text-primary text-sm ${fullMessage ? '' : 'truncate'}`}>
          {displayMessage}
        </p>
        <div className="flex items-center gap-2 text-text-muted text-xs mt-1">
          <span>
            {alert.sensor_name || 'System'}, {alert.location_name}
          </span>
          <span>&middot;</span>
          <RelativeTime timestamp={alert.alert_time} />
        </div>
      </div>

      {fullMessage && alert.trigger_value && (
        <div className="text-right shrink-0 mt-2 sm:mt-0">
          <div className="text-xs text-text-secondary uppercase">Trigger</div>
          <div className="font-data text-sm font-bold bg-surface-primary px-2 py-1 rounded border border-border-subtle mt-1">
            {Number(alert.trigger_value).toFixed(1)} {alert.unit}
          </div>
        </div>
      )}
    </div>
  );
}
